name: Oracle Reports Automation

on:
  schedule:
    # Corre a las 13:00 UTC = 07:00 hora CDMX (sin DST) de L-V
    - cron: '0 13 * * 1-5'
  workflow_dispatch:  # Permite lanzarlo manualmente

jobs:
  run-oracle-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas google-colab

      - name: Run Oracle automation script
        env:
          ORACLE_KEY: ${{ secrets.ORACLE_KEY }}
        run: |
          python oracle_reports_automation.py
