name: Oracle Reports Automation

on:
  schedule:
    # 13:00 UTC = 07:00 CDMX (lun-vie)
    - cron: '0 13 * * 1-5'
  workflow_dispatch:        # para disparo manual

jobs:
  run-oracle-reports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # ▸ Instalar dependencias -------------------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt   # <── usa tu archivo de 2 líneas
    # --------------------------------------------------------

    # (opcional) Instalar Google Chrome + ChromeDriver
    - name: Install Chrome & ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable unzip xvfb
        CHROME_MAJOR=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
        DRIVER_URL="https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR})/chromedriver_linux64.zip"
        curl -s -o /tmp/chromedriver.zip $DRIVER_URL
        unzip -q /tmp/chromedriver.zip -d /tmp
        sudo mv /tmp/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Oracle automation script
      env:
        ORACLE_KEY: ${{ secrets.ORACLE_KEY }}
      run: |
        python oracle_reports_automation.py
