name: Oracle Reports Automation

on:
  schedule:
    # 13:00 UTC = 07:00 h CDMX (lun-vie)
    - cron: '0 13 * * 1-5'
  workflow_dispatch:       # permite lanzarlo manualmente

jobs:
  run-oracle-reports:
    runs-on: ubuntu-latest

    steps:
    # 1. Traer el c칩digo del repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. Instalar dependencias listadas en requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Instalar Google Chrome estable
    - name: Set up Google Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable   # puedes fijar otra versi칩n si lo necesitas

    # 5. Instalar ChromeDriver compatible
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: latest

    # 6. Ejecutar tu script de automatizaci칩n
    - name: Run Oracle automation script
      env:
        ORACLE_KEY: ${{ secrets.ORACLE_KEY }}   # contrase침a guardada en Secrets
      run: |
        python oracle_reports_automation.py
